name: Mirror to GitLab

on:
  push:
    branches:
      - main
      - develop
      - sit
      - staging
      - pat

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ secrets.GITLAB_USERNAME }}/mftrade.git
          git push gitlab ${{ github.ref_name }} --force
